### ISSUE TITLE
Autoloader not working

### ISSUE THREAD

**Issue by 0Zinc** [WordPress/Requests#394] opened 2020-07-26 11:16 UTC
I have this code in my php:
```
require_once 'inc/Requests.php';
Requests::register_autoloader();
```

Yet I am still getting this error:
`PHP Fatal error:  Uncaught Error: Class 'Requests_Hooks' not found in /var/www/html/project/inc/Requests.php:568`

**Comment by jrfnl** [comment] 2020-10-18 01:55
Looks like a duplicate of #304

**Comment by jrfnl** [comment] 2021-09-18 15:09
@0Zinc The autoloading for Requests has been changed for Requests 2.0.0.

If you have the chance, it would be great if you would be able to test the current `develop` version of Requests to see if the problem has been fixed.

Upgrading instructions can be found here: https://github.com/WordPress/Requests/blob/develop/docs/upgrading.md

**Comment by jrfnl** [comment] 2021-11-25 12:32
I'm going to close this issue now Requests 2.0.0 has been released. The autoloading has been changed in Requests 2.0.0, so this issue should be considered superseded.

If you still see issues with autoloading when using Requests 2.0.0, please open a new issue.

**Closed by jrfnl** 2021-11-25 12:32 UTC
Labels: Type: support
