### ISSUE TITLE
303 should change method to GET

### ISSUE THREAD

**Issue by rmccue** [WordPress/Requests#7] opened 2012-02-08 07:04 UTC
As per RFC 2616, a `303 See Other` should have the method changed to GET.

**Comment by jrfnl** [comment] 2022-02-28 19:00
Looks like this _should_ be supported by httpbin by now: https://github.com/postmanlabs/httpbin/commit/b2cb8678f37f0c49e0df4637632106b5e1623070

The upstream support needs to be tested & confirmed and then this can (finally) be actioned.

**Comment by jrfnl** [comment] 2022-02-28 19:37
Looks like the actual change was already made in https://github.com/WordPress/Requests/commit/969bfdfdc27519226c1ed9b471b4097ab3b0205a. The test for this has now been added via PR #316. Closing!

**Closed by jrfnl** 2022-02-28 19:37 UTC
Labels: Component: Core
